# Author: together08
# Date: 2020-04-14
# Time: 08:46

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-1, -21, 181, 571))
        self.groupBox.setObjectName("groupBox")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(0, 20, 181, 531))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 240, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 330, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 360, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 440, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 470, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 500, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(50, 310, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(50, 420, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 180, 181, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 51, 51))
        self.label_16.setStyleSheet("")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 210, 41, 41))
        self.label_12.setStyleSheet("")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("images/Connect.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 300, 41, 41))
        self.label_15.setStyleSheet("")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("images/Settings.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 410, 41, 41))
        self.label_14.setStyleSheet("")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("images/About.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 190, 81, 71))
        self.label_9.setStyleSheet("image: url(:/about/images/About.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.action_6)
        self.menu_3.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Passwall"))
        MainWindow.setStatusTip(_translate("MainWindow", "一个基于Python Qt5编写的Passwall软件~"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "    Passwall"))
        self.label_5.setText(_translate("MainWindow", "连接------"))
        self.label_2.setText(_translate("MainWindow", " 一个功能完善的FQ软件，"))
        self.pushButton.setStatusTip(_translate("MainWindow", "所有的Passwall连接~"))
        self.pushButton.setText(_translate("MainWindow", "可用连接"))
        self.pushButton_8.setStatusTip(_translate("MainWindow", "订阅链接在这里删除添加~"))
        self.pushButton_8.setText(_translate("MainWindow", "订阅配置"))
        self.pushButton_7.setStatusTip(_translate("MainWindow", "代理有问题？来这里设置~"))
        self.pushButton_7.setText(_translate("MainWindow", "代理设置"))
        self.label_6.setText(_translate("MainWindow", " 助你快速稳定科学上网。"))
        self.pushButton_4.setStatusTip(_translate("MainWindow", "使用有问题？来这里看看吧~"))
        self.pushButton_4.setText(_translate("MainWindow", "帮助"))
        self.pushButton_6.setStatusTip(_translate("MainWindow", "贡献者-赞助一点也好啊（大雾"))
        self.pushButton_6.setText(_translate("MainWindow", "贡献者"))
        self.pushButton_5.setStatusTip(_translate("MainWindow", "你知道这款程序的来历吗？"))
        self.pushButton_5.setText(_translate("MainWindow", "开发背景"))
        self.label_7.setText(_translate("MainWindow", "配置------"))
        self.label_8.setText(_translate("MainWindow", "关于------"))
        self.label_3.setText(_translate("MainWindow", "------分割线------"))
        self.label_4.setText(_translate("MainWindow", " Surf the Internet~~~"))
        self.menu.setTitle(_translate("MainWindow", "连接"))
        self.menu_2.setTitle(_translate("MainWindow", "配置"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.statusbar.setStatusTip(_translate("MainWindow", "一个基于Python Qt5的Passwall软件~"))
        self.action.setText(_translate("MainWindow", "可用连接"))
        self.action.setStatusTip(_translate("MainWindow", "aaa"))
        self.action_3.setText(_translate("MainWindow", "代理设置"))
        self.action_4.setText(_translate("MainWindow", "订阅配置"))
        self.action_5.setText(_translate("MainWindow", "帮助"))
        self.action_6.setText(_translate("MainWindow", "贡献者"))
        self.action_7.setText(_translate("MainWindow", "开发背景"))
