# Author: together08
# Time: 18:15

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Passwall_MainWindow(object):
    def setupUi(self, Passwall_MainWindow):
        Passwall_MainWindow.setObjectName("Passwall_MainWindow")
        Passwall_MainWindow.resize(778, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Passwall_MainWindow.setWindowIcon(icon)
        self.Passwall_Centralwidget = QtWidgets.QWidget(Passwall_MainWindow)
        self.Passwall_Centralwidget.setObjectName("Passwall_Centralwidget")
        self.MainMenu_GroupBox = QtWidgets.QGroupBox(self.Passwall_Centralwidget)
        self.MainMenu_GroupBox.setGeometry(QtCore.QRect(-1, -21, 181, 571))
        self.MainMenu_GroupBox.setObjectName("MainMenu_GroupBox")
        self.MainMenu_ListView = QtWidgets.QListView(self.MainMenu_GroupBox)
        self.MainMenu_ListView.setGeometry(QtCore.QRect(0, 20, 181, 531))
        self.MainMenu_ListView.setObjectName("MainMenu_ListView")
        self.Passwall_Label = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Passwall_Label.setGeometry(QtCore.QRect(50, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Passwall_Label.setFont(font)
        self.Passwall_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Passwall_Label.setObjectName("Passwall_Label")
        self.Connect_Label = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Connect_Label.setGeometry(QtCore.QRect(50, 220, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.Connect_Label.setFont(font)
        self.Connect_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Connect_Label.setObjectName("Connect_Label")
        self.Introduce_2 = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Introduce_2.setGeometry(QtCore.QRect(0, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.Introduce_2.setFont(font)
        self.Introduce_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Introduce_2.setObjectName("Introduce_2")
        self.Canuse_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Canuse_PushButton.setGeometry(QtCore.QRect(0, 240, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.Canuse_PushButton.setFont(font)
        self.Canuse_PushButton.setDefault(False)
        self.Canuse_PushButton.setFlat(True)
        self.Canuse_PushButton.setObjectName("Canuse_PushButton")
        self.Subset_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Subset_PushButton.setGeometry(QtCore.QRect(0, 330, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Subset_PushButton.setFont(font)
        self.Subset_PushButton.setFlat(True)
        self.Subset_PushButton.setObjectName("Subset_PushButton")
        self.Proxyset_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Proxyset_PushButton.setGeometry(QtCore.QRect(0, 360, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Proxyset_PushButton.setFont(font)
        self.Proxyset_PushButton.setFlat(True)
        self.Proxyset_PushButton.setObjectName("Proxyset_PushButton")
        self.Inteoduce_3 = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Inteoduce_3.setGeometry(QtCore.QRect(0, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.Inteoduce_3.setFont(font)
        self.Inteoduce_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Inteoduce_3.setObjectName("Inteoduce_3")
        self.Help_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Help_PushButton.setGeometry(QtCore.QRect(0, 440, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Help_PushButton.setFont(font)
        self.Help_PushButton.setFlat(True)
        self.Help_PushButton.setObjectName("Help_PushButton")
        self.Maintainer_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Maintainer_PushButton.setGeometry(QtCore.QRect(0, 470, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Maintainer_PushButton.setFont(font)
        self.Maintainer_PushButton.setFlat(True)
        self.Maintainer_PushButton.setObjectName("Maintainer_PushButton")
        self.devbg_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.devbg_PushButton.setGeometry(QtCore.QRect(0, 500, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.devbg_PushButton.setFont(font)
        self.devbg_PushButton.setFlat(True)
        self.devbg_PushButton.setObjectName("devbg_PushButton")
        self.Settings_Label = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Settings_Label.setGeometry(QtCore.QRect(50, 310, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.Settings_Label.setFont(font)
        self.Settings_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Settings_Label.setObjectName("Settings_Label")
        self.About_Label = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.About_Label.setGeometry(QtCore.QRect(50, 420, 101, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setUnderline(False)
        self.About_Label.setFont(font)
        self.About_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.About_Label.setObjectName("About_Label")
        self.Separator_1 = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Separator_1.setGeometry(QtCore.QRect(0, 180, 181, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Separator_1.setFont(font)
        self.Separator_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Separator_1.setObjectName("Separator_1")
        self.Introduce_1 = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Introduce_1.setGeometry(QtCore.QRect(0, 60, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Introduce_1.setFont(font)
        self.Introduce_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Introduce_1.setObjectName("Introduce_1")
        self.Passwall_Logo = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Passwall_Logo.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.Passwall_Logo.setStyleSheet("")
        self.Passwall_Logo.setText("")
        self.Passwall_Logo.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.Passwall_Logo.setScaledContents(True)
        self.Passwall_Logo.setObjectName("Passwall_Logo")
        self.Connect_Logo = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Connect_Logo.setGeometry(QtCore.QRect(10, 220, 31, 31))
        self.Connect_Logo.setStyleSheet("")
        self.Connect_Logo.setText("")
        self.Connect_Logo.setPixmap(QtGui.QPixmap("images/Connect.png"))
        self.Connect_Logo.setScaledContents(True)
        self.Connect_Logo.setObjectName("Connect_Logo")
        self.Settings_Logo = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.Settings_Logo.setGeometry(QtCore.QRect(10, 310, 31, 31))
        self.Settings_Logo.setStyleSheet("")
        self.Settings_Logo.setText("")
        self.Settings_Logo.setPixmap(QtGui.QPixmap("images/Settings.png"))
        self.Settings_Logo.setScaledContents(True)
        self.Settings_Logo.setObjectName("Settings_Logo")
        self.About_Logo = QtWidgets.QLabel(self.MainMenu_GroupBox)
        self.About_Logo.setGeometry(QtCore.QRect(10, 420, 31, 31))
        self.About_Logo.setStyleSheet("")
        self.About_Logo.setText("")
        self.About_Logo.setPixmap(QtGui.QPixmap("images/About.png"))
        self.About_Logo.setScaledContents(True)
        self.About_Logo.setObjectName("About_Logo")
        self.Ping_PushButton = QtWidgets.QPushButton(self.MainMenu_GroupBox)
        self.Ping_PushButton.setGeometry(QtCore.QRect(0, 270, 181, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.Ping_PushButton.setFont(font)
        self.Ping_PushButton.setDefault(False)
        self.Ping_PushButton.setFlat(True)
        self.Ping_PushButton.setObjectName("Ping_PushButton")
        self.Widgets_Groupbox = QtWidgets.QGroupBox(self.Passwall_Centralwidget)
        self.Widgets_Groupbox.setGeometry(QtCore.QRect(180, 0, 910, 569))
        self.Widgets_Groupbox.setTitle("")
        self.Widgets_Groupbox.setObjectName("Widgets_Groupbox")
        self.ConnectStatus_Widget = QtWidgets.QWidget(self.Widgets_Groupbox)
        self.ConnectStatus_Widget.setGeometry(QtCore.QRect(0, 130, 291, 161))
        self.ConnectStatus_Widget.setObjectName("ConnectStatus_Widget")
        self.Allconnects_Number = QtWidgets.QLCDNumber(self.ConnectStatus_Widget)
        self.Allconnects_Number.setGeometry(QtCore.QRect(20, 90, 121, 51))
        self.Allconnects_Number.setObjectName("Allconnects_Number")
        self.CanuseConnects_Number = QtWidgets.QLCDNumber(self.ConnectStatus_Widget)
        self.CanuseConnects_Number.setGeometry(QtCore.QRect(150, 90, 121, 51))
        self.CanuseConnects_Number.setObjectName("CanuseConnects_Number")
        self.AllConnects_Label = QtWidgets.QLabel(self.ConnectStatus_Widget)
        self.AllConnects_Label.setGeometry(QtCore.QRect(20, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.AllConnects_Label.setFont(font)
        self.AllConnects_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.AllConnects_Label.setObjectName("AllConnects_Label")
        self.Canuseconnects_Label = QtWidgets.QLabel(self.ConnectStatus_Widget)
        self.Canuseconnects_Label.setGeometry(QtCore.QRect(150, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.Canuseconnects_Label.setFont(font)
        self.Canuseconnects_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Canuseconnects_Label.setObjectName("Canuseconnects_Label")
        self.Connectstatus_Label = QtWidgets.QLabel(self.ConnectStatus_Widget)
        self.Connectstatus_Label.setGeometry(QtCore.QRect(0, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Connectstatus_Label.setFont(font)
        self.Connectstatus_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Connectstatus_Label.setObjectName("Connectstatus_Label")
        self.Config_Widget = QtWidgets.QWidget(self.Widgets_Groupbox)
        self.Config_Widget.setGeometry(QtCore.QRect(310, 130, 291, 161))
        self.Config_Widget.setObjectName("Config_Widget")
        self.Config_Label = QtWidgets.QLabel(self.Config_Widget)
        self.Config_Label.setGeometry(QtCore.QRect(0, 0, 291, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Config_Label.setFont(font)
        self.Config_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Config_Label.setObjectName("Config_Label")
        self.Proxyway_ComboBox = QtWidgets.QComboBox(self.Config_Widget)
        self.Proxyway_ComboBox.setGeometry(QtCore.QRect(10, 100, 81, 22))
        self.Proxyway_ComboBox.setObjectName("Proxyway_ComboBox")
        self.Proxyway_ComboBox.addItem("")
        self.Proxyway_ComboBox.addItem("")
        self.Proxyway_ComboBox.addItem("")
        self.Proxyway_ComboBox.addItem("")
        self.Proxyway_Label = QtWidgets.QLabel(self.Config_Widget)
        self.Proxyway_Label.setGeometry(QtCore.QRect(10, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.Proxyway_Label.setFont(font)
        self.Proxyway_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Proxyway_Label.setObjectName("Proxyway_Label")
        self.Ping_PushButton_2 = QtWidgets.QPushButton(self.Config_Widget)
        self.Ping_PushButton_2.setGeometry(QtCore.QRect(130, 49, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Ping_PushButton_2.setFont(font)
        self.Ping_PushButton_2.setStatusTip("")
        self.Ping_PushButton_2.setFlat(True)
        self.Ping_PushButton_2.setObjectName("Ping_PushButton_2")
        self.Uprules_PushButton = QtWidgets.QPushButton(self.Config_Widget)
        self.Uprules_PushButton.setGeometry(QtCore.QRect(130, 69, 91, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Uprules_PushButton.setFont(font)
        self.Uprules_PushButton.setStatusTip("")
        self.Uprules_PushButton.setFlat(True)
        self.Uprules_PushButton.setObjectName("Uprules_PushButton")
        self.Upcore_Pushbutton = QtWidgets.QPushButton(self.Config_Widget)
        self.Upcore_Pushbutton.setGeometry(QtCore.QRect(130, 89, 91, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Upcore_Pushbutton.setFont(font)
        self.Upcore_Pushbutton.setStatusTip("")
        self.Upcore_Pushbutton.setFlat(True)
        self.Upcore_Pushbutton.setObjectName("Upcore_Pushbutton")
        self.Upsub_PushButton = QtWidgets.QPushButton(self.Config_Widget)
        self.Upsub_PushButton.setGeometry(QtCore.QRect(130, 109, 91, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Upsub_PushButton.setFont(font)
        self.Upsub_PushButton.setStatusTip("")
        self.Upsub_PushButton.setFlat(True)
        self.Upsub_PushButton.setObjectName("Upsub_PushButton")
        self.Inputserver_PushButton = QtWidgets.QPushButton(self.Config_Widget)
        self.Inputserver_PushButton.setGeometry(QtCore.QRect(130, 129, 111, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setUnderline(True)
        self.Inputserver_PushButton.setFont(font)
        self.Inputserver_PushButton.setStatusTip("")
        self.Inputserver_PushButton.setFlat(True)
        self.Inputserver_PushButton.setObjectName("Inputserver_PushButton")
        self.Logo_Label = QtWidgets.QLabel(self.Widgets_Groupbox)
        self.Logo_Label.setGeometry(QtCore.QRect(40, 40, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Logo_Label.setFont(font)
        self.Logo_Label.setStyleSheet("")
        self.Logo_Label.setText("")
        self.Logo_Label.setPixmap(QtGui.QPixmap("images/proxy.png"))
        self.Logo_Label.setScaledContents(True)
        self.Logo_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_Label.setObjectName("Logo_Label")
        self.Introduce_Main = QtWidgets.QLabel(self.Widgets_Groupbox)
        self.Introduce_Main.setGeometry(QtCore.QRect(90, 40, 491, 71))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        self.Introduce_Main.setFont(font)
        self.Introduce_Main.setAlignment(QtCore.Qt.AlignCenter)
        self.Introduce_Main.setObjectName("Introduce_Main")
        self.Terminal_Widget = QtWidgets.QWidget(self.Widgets_Groupbox)
        self.Terminal_Widget.setGeometry(QtCore.QRect(0, 310, 601, 241))
        self.Terminal_Widget.setObjectName("Terminal_Widget")
        self.Terminal_Label = QtWidgets.QLabel(self.Terminal_Widget)
        self.Terminal_Label.setGeometry(QtCore.QRect(0, 0, 601, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Terminal_Label.setFont(font)
        self.Terminal_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Terminal_Label.setObjectName("Terminal_Label")
        self.Terminal_TextBrowser = QtWidgets.QTextBrowser(self.Terminal_Widget)
        self.Terminal_TextBrowser.setGeometry(QtCore.QRect(0, 30, 601, 201))
        self.Terminal_TextBrowser.setObjectName("Terminal_TextBrowser")
        Passwall_MainWindow.setCentralWidget(self.Passwall_Centralwidget)
        self.Mainmenu_Menubar = QtWidgets.QMenuBar(Passwall_MainWindow)
        self.Mainmenu_Menubar.setGeometry(QtCore.QRect(0, 0, 778, 23))
        self.Mainmenu_Menubar.setObjectName("Mainmenu_Menubar")
        self.Connect_Menu = QtWidgets.QMenu(self.Mainmenu_Menubar)
        self.Connect_Menu.setObjectName("Connect_Menu")
        self.Settings_Menu = QtWidgets.QMenu(self.Mainmenu_Menubar)
        self.Settings_Menu.setObjectName("Settings_Menu")
        self.About_Menu = QtWidgets.QMenu(self.Mainmenu_Menubar)
        self.About_Menu.setObjectName("About_Menu")
        Passwall_MainWindow.setMenuBar(self.Mainmenu_Menubar)
        self.Main_Statusbar = QtWidgets.QStatusBar(Passwall_MainWindow)
        self.Main_Statusbar.setObjectName("Main_Statusbar")
        Passwall_MainWindow.setStatusBar(self.Main_Statusbar)
        self.Canconnect_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Canconnect_Action.setStatusTip("aaa")
        self.Canconnect_Action.setObjectName("Canconnect_Action")
        self.Subset_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Subset_Action.setObjectName("Subset_Action")
        self.Proxyset_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Proxyset_Action.setObjectName("Proxyset_Action")
        self.Help_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Help_Action.setObjectName("Help_Action")
        self.Maintainer_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Maintainer_Action.setObjectName("Maintainer_Action")
        self.Devbg_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Devbg_Action.setObjectName("Devbg_Action")
        self.Ping_Action = QtWidgets.QAction(Passwall_MainWindow)
        self.Ping_Action.setObjectName("Ping_Action")
        self.Connect_Menu.addAction(self.Canconnect_Action)
        self.Connect_Menu.addAction(self.Ping_Action)
        self.Settings_Menu.addAction(self.Subset_Action)
        self.Settings_Menu.addAction(self.Proxyset_Action)
        self.About_Menu.addAction(self.Help_Action)
        self.About_Menu.addAction(self.Maintainer_Action)
        self.About_Menu.addAction(self.Devbg_Action)
        self.Mainmenu_Menubar.addAction(self.Connect_Menu.menuAction())
        self.Mainmenu_Menubar.addAction(self.Settings_Menu.menuAction())
        self.Mainmenu_Menubar.addAction(self.About_Menu.menuAction())

        self.retranslateUi(Passwall_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Passwall_MainWindow)

    def retranslateUi(self, Passwall_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Passwall_MainWindow.setWindowTitle(_translate("Passwall_MainWindow", "Passwall"))
        Passwall_MainWindow.setStatusTip(_translate("Passwall_MainWindow", "一个基于Python Qt5编写的Passwall软件~"))
        self.MainMenu_GroupBox.setTitle(_translate("Passwall_MainWindow", "GroupBox"))
        self.Passwall_Label.setText(_translate("Passwall_MainWindow", "    Passwall"))
        self.Connect_Label.setText(_translate("Passwall_MainWindow", "-----连接------"))
        self.Introduce_2.setText(_translate("Passwall_MainWindow", " 一个功能完善的FQ软件，"))
        self.Canuse_PushButton.setStatusTip(_translate("Passwall_MainWindow", "所有的Passwall连接~"))
        self.Canuse_PushButton.setText(_translate("Passwall_MainWindow", "可用连接"))
        self.Subset_PushButton.setStatusTip(_translate("Passwall_MainWindow", "订阅链接在这里删除添加~"))
        self.Subset_PushButton.setText(_translate("Passwall_MainWindow", "订阅配置"))
        self.Proxyset_PushButton.setStatusTip(_translate("Passwall_MainWindow", "代理有问题？来这里设置~"))
        self.Proxyset_PushButton.setText(_translate("Passwall_MainWindow", "代理设置"))
        self.Inteoduce_3.setText(_translate("Passwall_MainWindow", " 助你快速稳定科学上网。"))
        self.Help_PushButton.setStatusTip(_translate("Passwall_MainWindow", "使用有问题？来这里看看吧~"))
        self.Help_PushButton.setText(_translate("Passwall_MainWindow", "帮助"))
        self.Maintainer_PushButton.setStatusTip(_translate("Passwall_MainWindow", "贡献者-赞助一点也好啊（大雾"))
        self.Maintainer_PushButton.setText(_translate("Passwall_MainWindow", "贡献者"))
        self.devbg_PushButton.setStatusTip(_translate("Passwall_MainWindow", "你知道这款程序的来历吗？"))
        self.devbg_PushButton.setText(_translate("Passwall_MainWindow", "开发背景"))
        self.Settings_Label.setText(_translate("Passwall_MainWindow", "-----配置------"))
        self.About_Label.setText(_translate("Passwall_MainWindow", "-----关于------"))
        self.Separator_1.setText(_translate("Passwall_MainWindow", "------分割线------"))
        self.Introduce_1.setText(_translate("Passwall_MainWindow", " Surf the Internet~~~"))
        self.Ping_PushButton.setStatusTip(_translate("Passwall_MainWindow", "所有的Passwall连接~"))
        self.Ping_PushButton.setText(_translate("Passwall_MainWindow", "速度测试"))
        self.AllConnects_Label.setText(_translate("Passwall_MainWindow", "所有连接数量"))
        self.Canuseconnects_Label.setText(_translate("Passwall_MainWindow", "可用连接数量"))
        self.Connectstatus_Label.setText(_translate("Passwall_MainWindow", "-----------连接情况----------"))
        self.Config_Label.setText(_translate("Passwall_MainWindow", "-----------某些操作----------"))
        self.Proxyway_ComboBox.setItemText(0, _translate("Passwall_MainWindow", "请选择"))
        self.Proxyway_ComboBox.setItemText(1, _translate("Passwall_MainWindow", "1.全局代理模式"))
        self.Proxyway_ComboBox.setItemText(2, _translate("Passwall_MainWindow", "2.白名单（PAC）模式"))
        self.Proxyway_ComboBox.setItemText(3, _translate("Passwall_MainWindow", "3.直连模式"))
        self.Proxyway_Label.setText(_translate("Passwall_MainWindow", "代理方式"))
        self.Ping_PushButton_2.setText(_translate("Passwall_MainWindow", "1.速度测试"))
        self.Uprules_PushButton.setText(_translate("Passwall_MainWindow", "2.更新代理规则"))
        self.Upcore_Pushbutton.setText(_translate("Passwall_MainWindow", "3.更新代理核心"))
        self.Upsub_PushButton.setText(_translate("Passwall_MainWindow", "4.更新订阅节点"))
        self.Inputserver_PushButton.setText(_translate("Passwall_MainWindow", "5.剪贴板导入节点"))
        self.Introduce_Main.setText(_translate("Passwall_MainWindow", "        Passwall--让您的代理之路所向披靡"))
        self.Terminal_Label.setText(_translate("Passwall_MainWindow", "-----------操作终端----------"))
        self.Terminal_TextBrowser.setHtml(_translate("Passwall_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans CJK SC\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Connect_Menu.setTitle(_translate("Passwall_MainWindow", "连接"))
        self.Settings_Menu.setTitle(_translate("Passwall_MainWindow", "配置"))
        self.About_Menu.setTitle(_translate("Passwall_MainWindow", "关于"))
        self.Main_Statusbar.setStatusTip(_translate("Passwall_MainWindow", "一个基于Python Qt5的Passwall软件~"))
        self.Canconnect_Action.setText(_translate("Passwall_MainWindow", "可用连接"))
        self.Subset_Action.setText(_translate("Passwall_MainWindow", "代理设置"))
        self.Proxyset_Action.setText(_translate("Passwall_MainWindow", "订阅配置"))
        self.Help_Action.setText(_translate("Passwall_MainWindow", "帮助"))
        self.Maintainer_Action.setText(_translate("Passwall_MainWindow", "贡献者"))
        self.Devbg_Action.setText(_translate("Passwall_MainWindow", "开发背景"))
        self.Ping_Action.setText(_translate("Passwall_MainWindow", "速度测试"))

